/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting.summary;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

public class Chart extends JPanel {

    /**
     * Creates new form Chart
     */
    public Chart() {
        initComponents();
        data = new int[0][];
        shades = null;
        scales = null;
        max = 1;
    }

    public static final Color[] COLORS = new Color[]{
        new Color(200, 200, 200),
        new Color(150, 150, 150),
        new Color(100, 100, 100),
        new Color(50, 50, 50),
        new Color(0, 0, 0)
    };

    public static final int FULL_BLACK = 0;
    public static final int EMPTY = 1;
    public static final int FULL_GRAY = 2;

    public void paintIt(Graphics2D g) {
        int w = this.getWidth();
        int h = this.getHeight();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);

        if (data.length == 0) {
            return;
        }

        int wh = w / data.length + 1;
        int hs = h / max + 1;

        for (int x = 0; x < data.length; x++) {
            int[] d = data[x];
            int b = 0;
            int o = x * wh;
            for (int y = 0; y < shades.length; y++) {
                int v = d[y];
                if (v == 0) {
                    continue;
                }
                int j = v * hs * scales[y];

                drawRect(g, shades[y], o, h - b - j, wh, j);
                b += j;
            }
        }
    }

    private static void drawRect(Graphics2D g, int color, int x, int y, int w, int h) {
        switch (color) {
            case FULL_BLACK:
                g.setColor(Color.BLACK);
                g.fillRect(x, y, w, h);
                break;
            case FULL_GRAY:
                g.setColor(Color.LIGHT_GRAY);
                g.fillRect(x, y, w, h);
                break;
            case EMPTY:
                g.setColor(Color.BLACK);
                g.drawRect(x, y, w, h);
                break;
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        paintIt((Graphics2D) g);
    }

    private int max;

    public void setMax(int m) {
        max = m;
    }

    private int[][] data;

    public void setData(int[][] d) {
        data = d;
    }
    private int[] shades;

    public void setShades(int[] s) {
        shades = s;
    }

    private int[] scales;

    public void setScales(int[] s) {
        scales = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
