/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting.summary;

public class Display extends javax.swing.JPanel {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        name = "";
    }

    private String name;

    public void setType(String s) {
        name = s;
        nameField.setText(s);
    }

    public void loadData(TeamRecord r) {
        double[] p = r.getSuccesses(name);
        double[] f = r.getFailures(name);
        fSI.setText(String.format("%2.1f", p[0]));
        fS3.setText(String.format("%2.1f", p[1]));
        fSA.setText(String.format("%2.1f", p[2]));
        fFI.setText(String.format("%2.1f", f[0]));
        fF3.setText(String.format("%2.1f", f[1]));
        fFA.setText(String.format("%2.1f", f[2]));

        chart1.setMax(r.getMaxHeight(name));
        chart1.setShades(r.getShades(name));
        chart1.setData(r.getGraphData(name));
        chart1.setScales(r.getScales(name));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart1 = new scouting.summary.Chart();
        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fSI = new javax.swing.JLabel();
        fFI = new javax.swing.JLabel();
        fS3 = new javax.swing.JLabel();
        fF3 = new javax.swing.JLabel();
        fSA = new javax.swing.JLabel();
        fFA = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        javax.swing.GroupLayout chart1Layout = new javax.swing.GroupLayout(chart1);
        chart1.setLayout(chart1Layout);
        chart1Layout.setHorizontalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        chart1Layout.setVerticalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        add(chart1);

        jPanel1.setBackground(new java.awt.Color(242, 255, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 52));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        nameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nameField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameField.setText("WWWWW");
        nameField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nameField.setAlignmentX(0.5F);
        jPanel1.add(nameField);

        jPanel3.setAlignmentY(0.0F);
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        fSI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fSI.setText("SI");
        jPanel3.add(fSI);

        fFI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fFI.setText("FI");
        jPanel3.add(fFI);

        fS3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fS3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fS3.setText("S3");
        jPanel3.add(fS3);

        fF3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fF3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fF3.setText("F3");
        jPanel3.add(fF3);

        fSA.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        fSA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fSA.setText("SA");
        jPanel3.add(fSA);

        fFA.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        fFA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fFA.setText("FA");
        jPanel3.add(fFA);

        jPanel1.add(jPanel3);

        add(jPanel1);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private scouting.summary.Chart chart1;
    private javax.swing.JLabel fF3;
    private javax.swing.JLabel fFA;
    private javax.swing.JLabel fFI;
    private javax.swing.JLabel fS3;
    private javax.swing.JLabel fSA;
    private javax.swing.JLabel fSI;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameField;
    // End of variables declaration//GEN-END:variables
}
