/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting.summary;

public class Display extends javax.swing.JPanel {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }

    private GraphRules rules;

    public void setType(GraphRules g) {
        nameField.setText(g.getName());
        rules = g;
    }

    public void loadData(TeamRecord r) {
        if (r == null) {
            fSI.setText("+Last");
            fS3.setText("+Rec");
            fSA.setText("+All");
            fFI.setText("-Last");
            fF3.setText("-Rec");
            fFA.setText("-All");
            chart1.setData(new int[0][]);
            return;
        }
        double[] p = r.getSuccesses(rules);
        double[] f = r.getFailures(rules);
        fSI.setText(String.format("%2.1f", p[0]));
        fS3.setText(String.format("%2.1f", p[1]));
        fSA.setText(String.format("%2.1f", p[2]));
        fFI.setText(String.format("%2.1f", f[0]));
        fF3.setText(String.format("%2.1f", f[1]));
        fFA.setText(String.format("%2.1f", f[2]));

        chart1.setMax(r.getMaxHeight(rules));
        chart1.setShades(r.getShades(rules));
        chart1.setData(r.getGraphData(rules));
        chart1.setScales(r.getScales(rules));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart1 = new scouting.summary.Chart();
        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fSI = new javax.swing.JLabel();
        fFI = new javax.swing.JLabel();
        fS3 = new javax.swing.JLabel();
        fF3 = new javax.swing.JLabel();
        fSA = new javax.swing.JLabel();
        fFA = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        javax.swing.GroupLayout chart1Layout = new javax.swing.GroupLayout(chart1);
        chart1.setLayout(chart1Layout);
        chart1Layout.setHorizontalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        chart1Layout.setVerticalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        add(chart1);

        jPanel1.setBackground(new java.awt.Color(209, 209, 209));
        jPanel1.setMaximumSize(new java.awt.Dimension(80, 32789));
        jPanel1.setMinimumSize(new java.awt.Dimension(80, 64));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        nameField.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        nameField.setForeground(new java.awt.Color(0, 0, 0));
        nameField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameField.setText("WWWWW");
        nameField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nameField.setAlignmentX(0.5F);
        jPanel1.add(nameField);

        jPanel3.setAlignmentY(0.0F);
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        fSI.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        fSI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fSI.setText("+Last");
        jPanel3.add(fSI);

        fFI.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        fFI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fFI.setText("-Last");
        jPanel3.add(fFI);

        fS3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        fS3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fS3.setText("+Rec");
        jPanel3.add(fS3);

        fF3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        fF3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fF3.setText("-Rec");
        jPanel3.add(fF3);

        fSA.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        fSA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fSA.setText("+All");
        jPanel3.add(fSA);

        fFA.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        fFA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fFA.setText("-All");
        jPanel3.add(fFA);

        jPanel1.add(jPanel3);

        add(jPanel1);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private scouting.summary.Chart chart1;
    private javax.swing.JLabel fF3;
    private javax.swing.JLabel fFA;
    private javax.swing.JLabel fFI;
    private javax.swing.JLabel fS3;
    private javax.swing.JLabel fSA;
    private javax.swing.JLabel fSI;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameField;
    // End of variables declaration//GEN-END:variables
}
