/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting.summary;

public class TeamDisplay extends javax.swing.JPanel {

    /**
     * Creates new form TeamDisplay
     */
    public TeamDisplay() {
        initComponents();
        teamData = null;

        display1.setType(GraphRules.AutoRules);
        display2.setType(GraphRules.MiscRules);
        display3.setType(GraphRules.TrussRules);
        display4.setType(GraphRules.PickupRules);
        display5.setType(GraphRules.HighRules);
        display6.setType(GraphRules.LowRules);
    }

    private TeamRecord teamData;

    public void setTeam(TeamRecord team) {
        teamData = team;
        teamNum.setText(String.format("%d", teamData.getTeamNum()));
        loadStats();
        display1.loadData(teamData);
        display2.loadData(teamData);
        display3.loadData(teamData);
        display4.loadData(teamData);
        display5.loadData(teamData);
        display6.loadData(teamData);
        this.repaint();
    }

    private void loadStats() {
        String[] s = teamData.getScouting();
        StringBuilder k = new StringBuilder();
        k.append("<html>");
        if (s.length >= 1) {
            k.append(s[0]);
        }
        for (int i = 1; i < s.length; i++) {
            k.append("<br/>");
            k.append(s[i]);
        }
        k.append("</html>");

        statsText.setText(k.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        teamNum = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        statsText = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel2 = new javax.swing.JPanel();
        display1 = new scouting.summary.Display();
        display2 = new scouting.summary.Display();
        display3 = new scouting.summary.Display();
        display4 = new scouting.summary.Display();
        display5 = new scouting.summary.Display();
        display6 = new scouting.summary.Display();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(900, 200));
        setMinimumSize(new java.awt.Dimension(900, 200));
        setPreferredSize(new java.awt.Dimension(900, 200));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(150, 126));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        teamNum.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        teamNum.setText("?????");
        teamNum.setAlignmentX(0.5F);
        jPanel1.add(teamNum);
        jPanel1.add(filler1);

        statsText.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        statsText.setText("<html> Here go: pit scouting info <br/> So: what teams say they do <br/> But: not what they do do <br/> Like: what their bot could do </html>");
        statsText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        statsText.setAlignmentX(0.5F);
        statsText.setAlignmentY(0.0F);
        jPanel1.add(statsText);
        jPanel1.add(filler2);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(2, 3));
        jPanel2.add(display1);
        jPanel2.add(display2);
        jPanel2.add(display3);
        jPanel2.add(display4);
        jPanel2.add(display5);
        jPanel2.add(display6);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private scouting.summary.Display display1;
    private scouting.summary.Display display2;
    private scouting.summary.Display display3;
    private scouting.summary.Display display4;
    private scouting.summary.Display display5;
    private scouting.summary.Display display6;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel statsText;
    private javax.swing.JLabel teamNum;
    // End of variables declaration//GEN-END:variables
}
